Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-CleanupSha256 { param([Parameter(Mandatory)][string]$Path) (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Get-CleanupSize { param([Parameter(Mandatory)][string]$Path) if(Test-Path -LiteralPath $Path -PathType Leaf){return (Get-Item -LiteralPath $Path).Length}; [long]$n=0; Get-ChildItem -LiteralPath $Path -File -Recurse -Force -ErrorAction SilentlyContinue|ForEach-Object{$n+=$_.Length};$n }
function ConvertTo-CleanupPortablePath { param([string]$Path,[string]$RepositoryRoot,[string]$TargetRoot) $p=[IO.Path]::GetFullPath($Path);if($p.StartsWith($RepositoryRoot,[StringComparison]::OrdinalIgnoreCase)){return '%REPOSITORY_ROOT%'+$p.Substring($RepositoryRoot.Length)};if($p.StartsWith($TargetRoot,[StringComparison]::OrdinalIgnoreCase)){return '%KI_STACK_ROOT%'+$p.Substring($TargetRoot.Length)};$profile=[Environment]::GetFolderPath('UserProfile');if($p.StartsWith($profile,[StringComparison]::OrdinalIgnoreCase)){return '%USERPROFILE%'+$p.Substring($profile.Length)};$p }
function Test-CleanupProtected { param([string]$Path,[string]$RepositoryRoot,[string]$TargetRoot) $p=[IO.Path]::GetFullPath($Path).TrimEnd('\');$r=[IO.Path]::GetFullPath($RepositoryRoot).TrimEnd('\');$t=[IO.Path]::GetFullPath($TargetRoot).TrimEnd('\');$p.Equals($r,[StringComparison]::OrdinalIgnoreCase)-or$p.Equals($t,[StringComparison]::OrdinalIgnoreCase)-or$p.StartsWith($t+'\',[StringComparison]::OrdinalIgnoreCase)-or($p.StartsWith($r+'\',[StringComparison]::OrdinalIgnoreCase)-and-not$p.StartsWith((Join-Path $r '_import')+'\',[StringComparison]::OrdinalIgnoreCase)) }
function Get-CleanupDependencies {
 param([string]$Path,[string[]]$ReferenceFiles,[object[]]$Processes,[object[]]$Tasks,[string[]]$EnvironmentValues)
 $refs=[Collections.Generic.List[string]]::new();$needle=[IO.Path]::GetFullPath($Path)
 foreach($f in $ReferenceFiles){try{if((Get-Content -LiteralPath $f -Raw -ErrorAction Stop).IndexOf($needle,[StringComparison]::OrdinalIgnoreCase)-ge 0){$refs.Add("file:$f")}}catch{}}
 foreach($p in $Processes){if($p.Path-and([string]$p.Path).StartsWith($needle,[StringComparison]::OrdinalIgnoreCase)){$refs.Add("process:$($p.Id)")}}
 foreach($t in $Tasks){if(([string]$t.Execute+' '+[string]$t.Arguments).IndexOf($needle,[StringComparison]::OrdinalIgnoreCase)-ge 0){$refs.Add("task:$($t.TaskName)")}}
 foreach($v in $EnvironmentValues){if($v-and$v.IndexOf($needle,[StringComparison]::OrdinalIgnoreCase)-ge 0){$refs.Add('environment-variable')}}
 @($refs|Select-Object -Unique)
}
function New-CleanupFinding {
 param([string]$Path,[string]$Type,[string]$Classification,[string]$Reason,[string]$Action,[string]$RepositoryRoot,[string]$TargetRoot,[string[]]$Dependencies=@(),[string]$Origin='filesystem',[string]$Version='unknown',[string]$Risk='low',[string]$Backup='none')
 $item=$null;try{$item=Get-Item -LiteralPath $Path -Force -ErrorAction Stop}catch{}
 [pscustomobject][ordered]@{path=ConvertTo-CleanupPortablePath $Path $RepositoryRoot $TargetRoot;type=$Type;sizeBytes=if($item){Get-CleanupSize $item.FullName}else{0};lastModifiedUtc=if($item){$item.LastWriteTimeUtc.ToString('o')}else{$null};detectedVersion=$Version;origin=$Origin;currentUse=if($Dependencies.Count){'referenced'}else{'not-detected'};dependencies=@($Dependencies);classification=$Classification;reason=$Reason;proposedAction=$Action;estimatedBytesFreed=if($Classification-eq'SAFE_TO_DELETE'){if($item){Get-CleanupSize $item.FullName}else{0}}else{0};risk=$Risk;requiredBackup=$Backup}
}
function New-CleanupVirtualFinding {
 param([string]$Identity,[string]$Type,[string]$Classification,[string]$Reason,[string]$Action,[string[]]$Dependencies=@(),[string]$Risk='medium')
 [pscustomobject][ordered]@{path=$Identity;type=$Type;sizeBytes=0;lastModifiedUtc=$null;detectedVersion='unknown';origin='system-inventory';currentUse=if($Dependencies.Count){'referenced'}else{'not-detected'};dependencies=@($Dependencies);classification=$Classification;reason=$Reason;proposedAction=$Action;estimatedBytesFreed=0;risk=$Risk;requiredBackup='manual review'}
}
function Invoke-KIStackCleanupAudit {
 [CmdletBinding()]param([string]$RepositoryRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,[string]$TargetRoot='C:\KI-Stack',[string[]]$SearchRoots,[string]$OutputDirectory,[switch]$FixtureMode)
 if(-not$SearchRoots){$SearchRoots=@($TargetRoot,(Split-Path $RepositoryRoot -Parent),(Join-Path $RepositoryRoot '_import'),(Join-Path $env:USERPROFILE 'Downloads'),(Join-Path $env:USERPROFILE 'Desktop'),(Join-Path $env:USERPROFILE 'Documents'),$env:TEMP)|Where-Object{$_-and(Test-Path -LiteralPath $_)} }
 $referenceRoots=@((Join-Path $RepositoryRoot 'tools'),(Join-Path $RepositoryRoot 'scripts'),(Join-Path $RepositoryRoot 'docs'),(Join-Path $TargetRoot 'modules'),(Join-Path $TargetRoot 'installer'),(Join-Path $TargetRoot 'state'))|Where-Object{Test-Path -LiteralPath $_}
 $refs=if(@($referenceRoots).Count){@(Get-ChildItem -LiteralPath $referenceRoots -Recurse -File -Include *.json,*.cmd,*.ps1,*.psm1 -ErrorAction SilentlyContinue|Where-Object{$_.Length-lt 2MB}|Select-Object -ExpandProperty FullName)}else{@()}
 $processes=@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Select-Object ProcessId,@{n='Id';e={$_.ProcessId}},ExecutablePath,@{n='Path';e={$_.ExecutablePath}},CommandLine)
 $tasks=@();if(-not$FixtureMode){$tasks=@(Get-ScheduledTask -ErrorAction SilentlyContinue|ForEach-Object{$task=$_;foreach($a in @($task.Actions)){[pscustomobject]@{TaskName=$task.TaskName;Execute=if($a.PSObject.Properties['Execute']){$a.Execute}else{$null};Arguments=if($a.PSObject.Properties['Arguments']){$a.Arguments}else{$null}}}})}
 $envValues=@([Environment]::GetEnvironmentVariables('User').Values)+@([Environment]::GetEnvironmentVariables('Machine').Values)
 $findings=[Collections.Generic.List[object]]::new();$seen=@{}
 foreach($root in $SearchRoots){if(-not(Test-Path -LiteralPath $root)){continue};$candidates=@(Get-ChildItem -LiteralPath $root -Force -ErrorAction SilentlyContinue);if([IO.Path]::GetFullPath($root).Equals([IO.Path]::GetFullPath($TargetRoot),[StringComparison]::OrdinalIgnoreCase)){$candidates=@(Get-Item -LiteralPath $root)}
  foreach($item in $candidates){$p=$item.FullName;if($item.Name-eq'desktop.ini'-or-not(Test-Path -LiteralPath $p)){continue};$name=$item.Name;$rootFull=[IO.Path]::GetFullPath($root);$isUserBroad=($rootFull-eq[IO.Path]::GetFullPath((Join-Path $env:USERPROFILE 'Downloads'))-or$rootFull-eq[IO.Path]::GetFullPath((Join-Path $env:USERPROFILE 'Desktop'))-or$rootFull-eq[IO.Path]::GetFullPath((Join-Path $env:USERPROFILE 'Documents'))-or$rootFull-eq[IO.Path]::GetFullPath($env:TEMP));if($isUserBroad-and$name-notmatch'(?i)KI[ -]?Stack|ComfyUI|OpenWebUI|SearXNG|LM[ -]?Studio|Execute|Recovery|Acceptance|Preflight|Target[ -]?Report|Validation|Agent[ -]?Pack|Image[ -]?Pack'){continue};if($seen[$p]){continue};$seen[$p]=$true;$deps=@(Get-CleanupDependencies $p $refs $processes $tasks $envValues)
   if(Test-CleanupProtected $p $RepositoryRoot $TargetRoot){$findings.Add((New-CleanupFinding $p 'protected-current' 'KEEP' 'Current production or repository content.' 'retain' $RepositoryRoot $TargetRoot $deps 'managed' 'current' 'critical' 'required')) ;continue}
   if(Test-Path -LiteralPath (Join-Path $p '.git')){$findings.Add((New-CleanupFinding $p 'git-worktree' 'BLOCKED' 'Foreign or separately owned Git worktree.' 'do-not-touch' $RepositoryRoot $TargetRoot $deps 'unknown' 'unknown' 'critical' 'owner decision'));continue}
   $isImport=$p.StartsWith((Join-Path $RepositoryRoot '_import'),[StringComparison]::OrdinalIgnoreCase)
   $isCache=($name-eq'__pycache__'-or$name-match '\.pyc$' -or $name-match '^(cache|tmp|temp)$')
   $isPackage=($name-match '(?i)KI-Stack|Execute|Recovery|Acceptance|Preflight|release|build|staging')
   if($deps.Count){$findings.Add((New-CleanupFinding $p 'referenced-candidate' 'BLOCKED' 'A current process, task, environment variable or file references this path.' 'do-not-touch' $RepositoryRoot $TargetRoot $deps 'dependency-scan' 'unknown' 'high' 'required'));continue}
   if($isCache){$findings.Add((New-CleanupFinding $p 'cache-or-temporary' 'SAFE_TO_DELETE' 'Explicit cache/temporary rule matched and no dependency was found.' 'quarantine-after-approval' $RepositoryRoot $TargetRoot $deps 'filesystem' 'unknown' 'low' 'quarantine'));continue}
   if($isImport){$findings.Add((New-CleanupFinding $p 'repository-import' 'ARCHIVE_RECOMMENDED' 'Ignored build or validation evidence may retain release value.' 'archive-or-quarantine-after-review' $RepositoryRoot $TargetRoot $deps 'repository-import' 'unknown' 'medium' 'archive'));continue}
   if($isPackage){$findings.Add((New-CleanupFinding $p 'legacy-package-candidate' 'ARCHIVE_RECOMMENDED' 'KI-Stack package/evidence candidate is inactive but may be useful for rollback evidence.' 'archive-after-review' $RepositoryRoot $TargetRoot $deps 'filesystem' 'unknown' 'medium' 'archive'));continue}
   $findings.Add((New-CleanupFinding $p 'unresolved-candidate' 'MANUAL_DECISION' 'Ownership or KI-Stack relationship is not unambiguous.' 'manual-review' $RepositoryRoot $TargetRoot $deps 'filesystem' 'unknown' 'high' 'owner decision'))
  }
 }
 if(-not$FixtureMode){
  foreach($p in $processes|Where-Object{([string]$_.Path+' '+[string]$_.CommandLine)-match'(?i)KI-Stack|ComfyUI|open-webui|searxng'}){$findings.Add((New-CleanupVirtualFinding ("process:{0}:{1}"-f$p.Id,([IO.Path]::GetFileName([string]$p.Path))) 'running-process' 'KEEP' 'Running component process; no cleanup action is allowed.' 'retain' @([string]$p.Path) 'critical'))}
  foreach($t in $tasks|Where-Object{([string]$_.TaskName+' '+[string]$_.Execute+' '+[string]$_.Arguments)-match'(?i)KI-Stack|ComfyUI|OpenWebUI|SearXNG'}){$findings.Add((New-CleanupVirtualFinding ("scheduled-task:{0}"-f$t.TaskName) 'scheduled-task' 'BLOCKED' 'Relevant scheduled task requires explicit ownership review.' 'do-not-touch' @([string]$t.Execute,[string]$t.Arguments) 'high'))}
  foreach($scope in 'User','Machine'){foreach($entry in [Environment]::GetEnvironmentVariables($scope).GetEnumerator()|Where-Object{([string]$_.Key+' '+[string]$_.Value)-match'(?i)KI-Stack|ComfyUI|OpenWebUI|SearXNG'}){$findings.Add((New-CleanupVirtualFinding ("environment:{0}:{1}"-f$scope,$entry.Key) 'environment-variable' 'MANUAL_DECISION' 'Relevant environment variable cannot be changed automatically.' 'manual-review' @() 'high'))}}
  try{foreach($fw in Get-NetFirewallRule -ErrorAction Stop|Where-Object{$_.DisplayName-match'(?i)KI-Stack|ComfyUI|OpenWebUI|SearXNG'}){$class=if($fw.Enabled-eq'True'){'BLOCKED'}else{'MANUAL_DECISION'};$findings.Add((New-CleanupVirtualFinding ("firewall:{0}"-f$fw.DisplayName) 'firewall-rule' $class 'Relevant firewall rule requires explicit dependency review.' 'do-not-touch' @() 'high'))}}catch{}
  try{foreach($d in @(& wsl.exe --list --quiet 2>$null)|ForEach-Object{$_.Trim([char]0).Trim()}|Where-Object{$_}){$class=if($_-eq'Debian'){'KEEP'}else{'MANUAL_DECISION'};$findings.Add((New-CleanupVirtualFinding ("wsl:{0}"-f$_) 'wsl-distribution' $class $(if($class-eq'KEEP'){'Current Integration distribution.'}else{'Non-current distribution; ownership is unresolved.'}) $(if($class-eq'KEEP'){'retain'}else{'manual-review'}) @() 'critical'))}}catch{}
  foreach($port in 80,1234,8080,8188){foreach($c in Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue){$findings.Add((New-CleanupVirtualFinding ("port:{0}:pid:{1}"-f$port,$c.OwningProcess) 'listening-port' 'KEEP' 'Current KI-Stack endpoint listener.' 'retain' @("process:$($c.OwningProcess)") 'critical'))}}
 }
 $counts=[ordered]@{};foreach($c in 'KEEP','SAFE_TO_DELETE','ARCHIVE_RECOMMENDED','MANUAL_DECISION','BLOCKED'){$counts[$c]=@($findings|Where-Object classification -eq $c).Count}
 $report=[pscustomobject][ordered]@{schemaVersion='1.0';version='1.0.0';status='AuditCompletedPendingCleanupApproval';generatedAtUtc=[DateTime]::UtcNow.ToString('o');searchRoots=@($SearchRoots|ForEach-Object{ConvertTo-CleanupPortablePath $_ $RepositoryRoot $TargetRoot});findings=@($findings);summary=@{counts=$counts;estimatedBytesFreed=[long](($findings|Measure-Object estimatedBytesFreed -Sum).Sum)};protectedPaths=@('%KI_STACK_ROOT%','%REPOSITORY_ROOT%','%KI_STACK_ROOT%\OpenWebUI\data','%KI_STACK_ROOT%\models','%KI_STACK_ROOT%\data\comfyui','%KI_STACK_ROOT%\python\venvs','%KI_STACK_ROOT%\modules');manualDecisions=@($findings|Where-Object classification -eq MANUAL_DECISION|Select-Object -ExpandProperty path);mutatesSystem=$false}
 if($OutputDirectory){New-Item -ItemType Directory -Path $OutputDirectory -Force|Out-Null;$auditPath=Join-Path $OutputDirectory 'system-cleanup-audit.json';$report|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $auditPath -Encoding utf8;$auditSha=Get-CleanupSha256 $auditPath;$entries=@($findings|Where-Object classification -eq SAFE_TO_DELETE|ForEach-Object{[pscustomobject]@{path=$_.path;expectedSizeBytes=$_.sizeBytes;classification=$_.classification;action='quarantine';precondition='unchanged-and-unreferenced'}});$plan=[pscustomobject][ordered]@{schemaVersion='1.0';version='1.0.0';status='PendingCleanupApproval';generatedAtUtc=[DateTime]::UtcNow.ToString('o');auditSha256=$auditSha;approved=$false;quarantineRoot='C:\KI-Stack-Cleanup-Quarantine\<TransactionId>';entries=$entries;estimatedBytesFreed=$report.summary.estimatedBytesFreed};$planPath=Join-Path $OutputDirectory 'system-cleanup-plan.json';$plan|ConvertTo-Json -Depth 12|Set-Content -LiteralPath $planPath -Encoding utf8;return [pscustomobject]@{report=$report;auditPath=$auditPath;planPath=$planPath;planSha256=Get-CleanupSha256 $planPath}}
 $report
}
function Invoke-KIStackCleanupExecute {
 [CmdletBinding(SupportsShouldProcess)]param([Parameter(Mandatory)][string]$PlanPath,[Parameter(Mandatory)][string]$ExpectedPlanSha256,[string]$TransactionId=('CLEANUP-'+[DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss')),[string]$QuarantineRoot='C:\KI-Stack-Cleanup-Quarantine')
 if((Get-CleanupSha256 $PlanPath)-ne$ExpectedPlanSha256.ToLowerInvariant()){throw'Plan SHA256 mismatch.'};$plan=Get-Content -LiteralPath $PlanPath -Raw|ConvertFrom-Json;if(-not$plan.approved){throw'Plan is not approved; Execute is blocked.'};throw'Execute remains disabled pending explicit cleanup approval.'
}
function Restore-KIStackCleanup { [CmdletBinding()]param([Parameter(Mandatory)][string]$RollbackPath) $r=Get-Content -LiteralPath $RollbackPath -Raw|ConvertFrom-Json;foreach($m in @($r.moves)|Sort-Object sequence -Descending){if(Test-Path -LiteralPath $m.quarantinePath){if(Test-Path -LiteralPath $m.originalPath){throw"Rollback target exists: $($m.originalPath)"};Move-Item -LiteralPath $m.quarantinePath -Destination $m.originalPath}};[pscustomobject]@{status='RolledBack';transactionId=$r.transactionId} }
Export-ModuleMember -Function Invoke-KIStackCleanupAudit,Invoke-KIStackCleanupExecute,Restore-KIStackCleanup,Get-CleanupSha256
