[CmdletBinding()]
param([Parameter(Mandatory)][string]$PayloadSource,[Parameter(Mandatory)][string]$OutputDirectory)
$ErrorActionPreference='Stop';$version=(Get-Content (Join-Path $PSScriptRoot 'VERSION') -Raw).Trim();$contract=Get-Content (Join-Path $PSScriptRoot 'Contracts/PAYLOADS.json') -Raw|ConvertFrom-Json
$stage=Join-Path $env:TEMP ('KI-Stack-Ballistics-Build-'+[Guid]::NewGuid().ToString('N'));$root=Join-Path $stage "KI-Stack-OpenWebUI-Ballistics-Pack-v$version";New-Item $root -ItemType Directory -Force|Out-Null
try {Copy-Item (Join-Path $PSScriptRoot '*') $root -Recurse -Force;Get-ChildItem $root -Recurse -Directory -Filter '__pycache__'|Remove-Item -Recurse -Force;Get-ChildItem $root -Recurse -File -Include '*.pyc','*.pyo'|Remove-Item -Force;Remove-Item (Join-Path $root 'Payload') -Recurse -Force -ErrorAction SilentlyContinue;New-Item (Join-Path $root 'Payload') -ItemType Directory|Out-Null;foreach($p in $contract.payloads){$src=Join-Path $PayloadSource ([string]$p.name);if(-not(Test-Path $src)){throw"Payload fehlt: $($p.name)"};if((Get-Item $src).Length-ne[long]$p.size-or(Get-FileHash $src -Algorithm SHA256).Hash-ne[string]$p.sha256){throw"Payloadvertrag verletzt: $($p.name)"};Copy-Item $src (Join-Path $root 'Payload')}
Remove-Item (Join-Path $root 'SHA256SUMS.txt') -Force -ErrorAction SilentlyContinue
$files=Get-ChildItem $root -Recurse -File|Sort-Object{[IO.Path]::GetRelativePath($root,$_.FullName)};$lines=$files|ForEach-Object{"$((Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant())  $([IO.Path]::GetRelativePath($root,$_.FullName).Replace('\','/'))"};[IO.File]::WriteAllLines((Join-Path $root 'SHA256SUMS.txt'),$lines,[Text.UTF8Encoding]::new($false))
New-Item $OutputDirectory -ItemType Directory -Force|Out-Null;$zip=Join-Path $OutputDirectory "KI-Stack-OpenWebUI-Ballistics-Pack-v$version.zip";Remove-Item $zip -Force -ErrorAction SilentlyContinue
Add-Type -AssemblyName System.IO.Compression;$fs=[IO.File]::Open($zip,[IO.FileMode]::CreateNew);$archive=[IO.Compression.ZipArchive]::new($fs,[IO.Compression.ZipArchiveMode]::Create);try{foreach($file in Get-ChildItem $root -Recurse -File|Sort-Object{[IO.Path]::GetRelativePath($stage,$_.FullName)}){$entryName=[IO.Path]::GetRelativePath($stage,$file.FullName).Replace('\','/');$entry=$archive.CreateEntry($entryName,[IO.Compression.CompressionLevel]::Optimal);$entry.LastWriteTime=[DateTimeOffset]::new(2026,7,22,0,0,0,[TimeSpan]::Zero);$input=$file.OpenRead();$output=$entry.Open();try{$input.CopyTo($output)}finally{$output.Dispose();$input.Dispose()}}}finally{$archive.Dispose();$fs.Dispose()}
$hash=(Get-FileHash $zip -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText("$zip.sha256","$hash  $([IO.Path]::GetFileName($zip))`n",[Text.UTF8Encoding]::new($false));[pscustomobject]@{version=$version;zip=$zip;sha256=$hash;payloadCount=$contract.payloads.Count}}finally{Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue}
